-- ================================================================
-- DDL: CRTIDX01.sql
-- DESCRIPTION: Additional indexes for Business Banking tables
-- ================================================================

CREATE INDEX IX_BAC_APP_STATUS
    ON TB_BAC_APPLICATION (APP_STATUS, APP_ID)
    USING STOGROUP BACIX;

CREATE INDEX IX_BAC_APP_BRANCH
    ON TB_BAC_APPLICATION (BRANCH_CODE, APP_STATUS)
    USING STOGROUP BACIX;

CREATE INDEX IX_BAC_CUST_APP
    ON TB_BAC_CUSTOMER (APP_ID)
    USING STOGROUP BACIX;

CREATE INDEX IX_BAC_SIG_APP
    ON TB_BAC_SIGNATORY (APP_ID)
    USING STOGROUP BACIX;

CREATE INDEX IX_BAC_ACC_CUST
    ON TB_BAC_ACCOUNT (CUST_ID)
    USING STOGROUP BACIX;

CREATE INDEX IX_BAC_DOC_APP
    ON TB_BAC_DOCUMENT (APP_ID)
    USING STOGROUP BACIX;

CREATE INDEX IX_BAC_CARD_ACCOUNT
    ON TB_BAC_CARD (ACCOUNT_NUMBER)
    USING STOGROUP BACIX;

CREATE INDEX IX_BAC_CARD_APP
    ON TB_BAC_CARD (APP_ID)
    USING STOGROUP BACIX;

CREATE INDEX IX_BAC_CARD_CUST
    ON TB_BAC_CARD (CUST_ID)
    USING STOGROUP BACIX;
