-- ================================================================
-- DDL: CRTTBL04.sql
-- TABLE: TB_BAC_ACCOUNT
-- DESCRIPTION: Opened account master
-- ================================================================

CREATE TABLE TB_BAC_ACCOUNT
(
    ACCOUNT_NUMBER      CHAR(12)        NOT NULL,
    APP_ID              CHAR(10)        NOT NULL,
    CUST_ID             CHAR(10)        NOT NULL,
    ACCOUNT_TYPE        CHAR(2),
    CURRENCY            CHAR(3),
    STATUS              CHAR(2)         DEFAULT 'AC',
    OPEN_DATE           DATE            NOT NULL DEFAULT CURRENT DATE,
    BALANCE             DECIMAL(13,2)   DEFAULT 0.00,
    AVAILABLE_BALANCE   DECIMAL(13,2)   DEFAULT 0.00,
    INITIAL_DEPOSIT     DECIMAL(13,2)   DEFAULT 0.00,
    BRANCH_CODE         CHAR(6),
    MAKER_ID            CHAR(8),
    CHECKER_ID          CHAR(8),
    CREATED_TIMESTAMP   TIMESTAMP       NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TIMESTAMP   TIMESTAMP       NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (ACCOUNT_NUMBER)
)
IN BACDB.BACTS01
CCSID EBCDIC;

ALTER TABLE TB_BAC_ACCOUNT
    ADD CONSTRAINT FK_BAC_ACC_APP
    FOREIGN KEY (APP_ID) REFERENCES TB_BAC_APPLICATION(APP_ID);

ALTER TABLE TB_BAC_ACCOUNT
    ADD CONSTRAINT FK_BAC_ACC_CUST
    FOREIGN KEY (CUST_ID) REFERENCES TB_BAC_CUSTOMER(CUST_ID);

ALTER TABLE TB_BAC_ACCOUNT
    ADD CONSTRAINT CK_BAC_ACC_STATUS
    CHECK (STATUS IN ('AC','CL','FR'));

COMMENT ON TABLE TB_BAC_ACCOUNT IS
    'Business Banking Account Master';
