-- ================================================================
-- DDL: CRTTBL07.sql
-- TABLE: TB_BAC_CARD
-- DATABASE: DB2 - Business Banking Debit / Prepaid Card Master
-- DESCRIPTION: Issued plastic card details linked to an account
-- ================================================================

CREATE TABLE TB_BAC_CARD
(
    CARD_ID             CHAR(10)        NOT NULL,
    APP_ID              CHAR(10)        NOT NULL,
    ACCOUNT_NUMBER      CHAR(12)        NOT NULL,
    CUST_ID             CHAR(10)        NOT NULL,
    CARD_NUMBER         CHAR(16)        NOT NULL,
    CARD_TYPE           CHAR(2)         NOT NULL DEFAULT 'DC',
    CARD_STATUS         CHAR(2)         NOT NULL DEFAULT 'RQ',
    PLASTIC_STATUS      CHAR(2)         DEFAULT 'PE',
    EMBOSS_NAME         VARCHAR(30),
    ISSUE_DATE          DATE            DEFAULT CURRENT DATE,
    EXPIRY_DATE         DATE,
    DAILY_LIMIT         DECIMAL(9,2)    DEFAULT 0.00,
    ATM_LIMIT           DECIMAL(9,2)    DEFAULT 0.00,
    MONTHLY_LIMIT       DECIMAL(11,2)   DEFAULT 0.00,
    AVAILABLE_LIMIT     DECIMAL(11,2)   DEFAULT 0.00,
    CVV                 CHAR(3),
    PIN_STATUS          CHAR(1)         DEFAULT 'N',
    ACTIVATION_STATUS   CHAR(1)         DEFAULT 'I',
    DISPATCH_STATUS     CHAR(2)         DEFAULT 'PD',
    MAKER_ID            CHAR(8),
    CHECKER_ID          CHAR(8),
    CREATED_TIMESTAMP   TIMESTAMP       NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TIMESTAMP   TIMESTAMP       NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (CARD_ID),
    CONSTRAINT UQ_BAC_CARD_NUMBER UNIQUE (CARD_NUMBER)
)
IN BACDB.BACTS01
CCSID EBCDIC;

ALTER TABLE TB_BAC_CARD
    ADD CONSTRAINT FK_BAC_CARD_APP
    FOREIGN KEY (APP_ID) REFERENCES TB_BAC_APPLICATION(APP_ID);

ALTER TABLE TB_BAC_CARD
    ADD CONSTRAINT FK_BAC_CARD_ACCOUNT
    FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES TB_BAC_ACCOUNT(ACCOUNT_NUMBER);

ALTER TABLE TB_BAC_CARD
    ADD CONSTRAINT FK_BAC_CARD_CUST
    FOREIGN KEY (CUST_ID) REFERENCES TB_BAC_CUSTOMER(CUST_ID);

ALTER TABLE TB_BAC_CARD
    ADD CONSTRAINT CK_BAC_CARD_STATUS
    CHECK (CARD_STATUS IN ('RQ','AP','IS','BL','CA'));

ALTER TABLE TB_BAC_CARD
    ADD CONSTRAINT CK_BAC_CARD_PLASTIC
    CHECK (PLASTIC_STATUS IN ('PE','EM','DI','DE','DA'));

ALTER TABLE TB_BAC_CARD
    ADD CONSTRAINT CK_BAC_CARD_TYPE
    CHECK (CARD_TYPE IN ('DC','CC','PC'));

COMMENT ON TABLE TB_BAC_CARD IS
    'Business Banking Debit / Prepaid Card Master';
