-- ================================================================
-- DML: QRYBAC01.sql
-- COMMON QUERIES FOR THE BUSINESS BANKING PORTAL                 *
-- ================================================================

-- 1. LIST ALL SUBMITTED/APPROVED APPLICATIONS READY FOR OPENING
SELECT APP_ID, BUSINESS_NAME, APP_STATUS, ACCOUNT_TYPE,
       INITIAL_DEPOSIT, RISK_RATING, BRANCH_CODE
FROM   TB_BAC_APPLICATION
WHERE  APP_STATUS IN ('SB','AP')
ORDER BY APP_ID;

-- 2. INQUIRY BY APPLICATION ID
SELECT A.*, C.CUST_ID, C.ACCOUNT_NUMBER
FROM   TB_BAC_APPLICATION A
LEFT JOIN TB_BAC_CUSTOMER C ON A.APP_ID = C.APP_ID
WHERE  A.APP_ID = 'APP0000001';

-- 3. LIST SIGNATORIES FOR AN APPLICATION
SELECT SIG_ID, NAME, TITLE, SIG_TYPE, OWNERSHIP_PCT, ID_TYPE
FROM   TB_BAC_SIGNATORY
WHERE  APP_ID = 'APP0000001';

-- 4. LIST DOCUMENT CHECKLIST STATUS
SELECT APP_ID, DOC_TYPE, STATUS, RECEIVED_DATE, REMARKS
FROM   TB_BAC_DOCUMENT
WHERE  APP_ID = 'APP0000001';

-- 5. LIST OPENED ACCOUNTS WITH CUSTOMER
SELECT A.ACCOUNT_NUMBER, C.BUSINESS_NAME, A.ACCOUNT_TYPE,
       A.OPEN_DATE, A.BALANCE, A.STATUS
FROM   TB_BAC_ACCOUNT A
JOIN   TB_BAC_CUSTOMER C ON A.CUST_ID = C.CUST_ID;

-- 6. AUDIT TRAIL FOR AN APPLICATION
SELECT APP_ID, STATUS_FROM, STATUS_TO, USER_ID, ACTION_TIMESTAMP,
       ACTION_TYPE, REMARKS
FROM   TB_BAC_AUDIT
WHERE  APP_ID = 'APP0000001'
ORDER BY ACTION_TIMESTAMP;
